[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anchor"
version = "0.1.0"
dependencies = []
[project.scripts]
  anchor = "anchor:main"